:PROPERTIES:
:ID:       05541cd1-e09a-45a2-b340-4e2b4a53ec3c
:END:
#+title: chadabe97_elect_sound:traditional_instruments
#+filetags: :tradition:

Why throw away tradition? Instead, use traditional instruments to control electronics and combine virtuosity with imaginative sounds? And bring electronic music into context of traditional music. Traditional instruments are there because people enjoy playing them and are extensions of ourselves. As John Chowning said, "it would be silly to throw away the keyboard simply because it's related to an older music -- you can apply people's keyboard facility in new and different ways."

Paul DeMarinis tells a story of creating a new style of electronic guitar, but no one took to it because it didn't look like a guitar. So he got a maker to put his new stuff in the body of a guitar, and suddenly everyone liked it.

Most of the people making music are doing it on traditional instruments, so pieces should aim towards their skill sets. 

cite:chadabe97_elect_sound
