:PROPERTIES:
:ID:       dcdf66d7-a677-485a-8dc8-1b0a31fdcf17
:END:
#+title: harries14-absence-presence
#+filetags: :absence:presence:dramaturgy:uncanny:sublime:


Live electroacoustic music has elements of presence and absence; the real and physical paired with the disembodied and simulated. Since live electroacoustic music is still part of the performance discipline, there is an element of creating meaning in the performance, or dramaturgy. These aspects of presence and absence can be used to create poetic meaning in the dramaturgy of the live performance. Two particular affects that are common are the uncanny and the sublime.

The uncanny is evoked when the familiar and unfamiliar are joined together, while the sublime is the tension of the familiar and that which cannot be grasped. There are many different ways electroacoustic music can bring these affects. Some options include evoking specific absentees, nostalgia, phantoms, silence, doubling, acousmatisation, or deacousmatisation.

Live electroacoustic music has certainly expanded the sound palette available in music, but through the characterisctics of absence and presence has the ability to expand the dramaturgy available in live musical performances. 

cite:harries14_evokin_sublim
