:PROPERTIES:
:ID:       1550d7a9-ba24-4b16-90ce-79a666498ceb
:END:
#+title: bocast12-piraha
#+filetags: :parahi:musilanguage:mental_health:evolution:

Music evolved to promote cognitive development, and perhaps have some forms of communication. The fact almost all humans still have music suggests an evolutional need for it.

A tribe of indians in Brazil, the Piraha, has language that is very musical. They have resisted cultural change, and show a high level of mental health. Other tribes around them do not show the same thing, and so something in their culture keeps them healthy. It is suggested that the constant musicality of their language has an effect.

Evolution has made many tradeoffs for the human species, often replacing a behavior with something more practical. Possibly, language evolved as being more practical than music for communication. However, there is a tradeoff to this cost. Music is being studied at being an effective treatment for anxiety and depression. 



cite:bocast12_examin_place_music_wester_eco
