:PROPERTIES:
:ID:       f4add163-6bc5-451b-b4b7-b313567f6ff2
:END:
#+title: reading list

- TODO Lou Skinner Reed Manual
- TODO Physical Forces at Work in Bassoon Reeds - James B. Kopp [[id:e9b73e82-8c15-4d43-9e0f-6ce367aa5eba][kopp03_physic_forces_at_work_bassoon_reeds]]
- TODO Popkin Book
- TODO Weaitt Book
- TODO Tuning Book
- TODO Massol Winstead article [[id:be5a8fcb-5d04-4b00-999b-fefbe68c9b7c][massol10_william_winst_bassoon_reed_method]]
- TODO Heinrich Geometry [[id:f89ea539-b31e-4dea-b7a3-f61796a81943][heinrich79_bassoon_reed]]
- TODO Kopp Tube Tip Aperture [[id:3bd499aa-8b63-4458-94b7-82ea6917b7ae][kopp13_tube_tip_apert]]
- TODO Bundle of Joy Chapter [[id:9f957943-d0e5-4331-bbff-63f47f923742][vonk07_bundl_joy]]
- TODO Points of Resistance [[id:27789022-6105-4c0e-b35c-817414a44500][clark00_point_resis_bassoon_reeds]]
- TODO Eubanks Reed Design [[id:903a565f-60fd-46d3-a8f7-152d5b522aa4][eubanks86_advan_reed_desig_testin_proced_bassoon]]

Christlieb, Don. "The Reed Problem." /Journal of IDRS/ 25 (1997): 83-84. (brief glance seems not too important)

Almenraeder, Karl. "On the Making of Bassoon Reeds." /Journal of the IDRS/ 8 (1980): 1-6.

Eifert, Otto, ed. "Memoirs and Homage to Lou Skinner." /The Double Reed/ 17, no. 1 (1994): 1-4.

Herzberg, Norman. "Years of Ignorance, Neglect and Denial: The Importance of Speaker Key Use on the Bassoon." /The Double Reed/ 18, no. 3 (1995): 53-63.
[[id:57c03c4a-4d0d-4e66-a6bd-050c088abc8e][herzberg95_years_ignor_neglec_denial]]

Intravaia, Lawrence. "The Effects of Hardness and Stiffness of Bassoon Cane upon Performance of the Reed." /Journal of IDRS/ 6 (1978): 30-46.
[[id:534e791b-b6ce-40cc-b7d6-2293c536eb6b][intravaia78_effec_hardn_stiff_bassoon_cane]]

Lyman Jeffrey, and Mark Clague. "Tributes to Lewis Hugh Cooper." /The Double Reed/ 30, no. 3 (2007): 29-39.

Morris, Matthew Blane. "The Teaching Methods of Lewis Hugh Cooper." DMA treatise, Florida State University, 2005. [[id:f5ef52d1-b1a0-4b07-b032-a50a5befd9da][morris05_teach_method_lewis_hugh_cooper]]

Rechtman, Mordechai. The Bassoon Reed "My System"

Cook, Nicholas. /A Guide to Musical Analysis/.

Cook, Nicholas. /Beyond the Score/.
