:PROPERTIES:
:ID:       bfc736a7-58cc-4256-a576-735e29c35a7f
:END:
#+title: idrs lecture

* Intro to Genre (2 min)
This lecture is called Interactive Electroacoustic Music for Bassoon, so what does that mean? Did anyone go to Dr. Seguin's performance yesterday? That's a great example of what we're talking about; music that involves some form of interaction with electronics to create music. There are various definitions for what a piece needs to be considered "interactive," but I think from the performer's perspective those distinctions are less important. I like to call any piece that requires the performer to trigger events as interactive. This includes pieces with computers as well as effects pedals, which are really just a differnet kind of computer. I find this music to be exciting for performers! This genre was developed in many ways to bring the human element into electronic music performance, and give more freedom to the performer. Has anyone ever played a piece with "tape" or fixed media? I think most performers find it a bit stressful, because there's no conductor to follow you, no adjustments that can be made in the accompaniment, nothing. It's right or wrong. That still exists in some parts of interactive pieces, but there is usually more control for the performer as well.
* 3 Parts of the System
But with that flexibility comes a bit more complexity, especially with technology, and that can be intimidating for performers. My goal is to try and remove some of the apprehension so more of you can start performing this great music. In my view, this performance system consists of three parts: input, processing, and output. Each part has many variations, but these three parts are the basic foundation of all interactive electroacoustic music.
** Input (total 9 minutes)
The input phase involves getting the sound of the bassoon (or any other instrument) to the computer so that the computer can do fun things. This basically means using a microphone of some sort, often two.
*** Microphones (4 min)
**** Types
There are many different types of micrphones that use different methods to capture sound and transmit them elsewhere. The main types are dynamic microphones, condenser microphones, and ribbon microphones. All of them can work. You can use a cheap $25 dynamic microphone or an $10,000  condenser. Now the sound quality between the two will not be identical, but both can work. Many people prefer using condenser microphones for acoustic instruments, as it tends to have the smoothest frequency response. Many microphones have a graph to show frequency response that looks like this. It shows how loud each frequency is represented in relation to the actual sound. So if the line is above 0db, it means the microphone picks up that frequency range louder than it really was, and if it's below 0db, then it's quieter. Ideally you want the smoothest line you can get. The bassoon's fundamental range is between 55 and 600Hz, but the overtones in the sound go up to 9kHz. So for this microphone you can see that the lowest notes will be a bit softer and the highest overtones accentuated. Most of the instruments range is pretty flat though. You will still hear the low notes on this microphone, just not as maybe a different microphone. This graph is for the Shure SM57, a $100 dynamic mic. Rachel Elliot has used two of these with good results. Just for comparison, here is the Rode NT-1's chart. It's more like $300, but has a better low end response. It will also have a different color than the SM 57 because of the difference in the overtones. More expensive microphones tend to have flatter response graphs and different colors to the sound, but it's not necessary to drop thousands of dollars on microphones, although you easily could.

There are also different recording modes called polar patterns. This more or less describes where microphones pick up sound from. Some microphones can record in an omnidirectional mode, meaning from everywhere. Other's have a figure-8 pattern that records what is in front and behind the microphone. What is usually desired in a live performance setting is called cardiod, or more of a heart shape. One reason is we want to minimize feedback, which happens when the microphone is picking up the sound from nearby speakers. We also probably don't want to record sounds from the audience behind the microphone.

So for using traditional microphones, we usually want cardiod condenser or dynamic microphones. Ribbons have a nice sound on the bassoon, but the figure-8 pattern might not be a good idea depending on the performance space. A common setup is to use two microphones, one that is pointed near the bell to capture the low end frequencies, and another that is pointed towards the middle of the bassoon at the toneholes.  
*** Electric Bocals (3 min)
An alternative form of capturing the bassoon sound is to use an electric bocal. This tends to work best with effects pedals, but can also work with computers. It works by listening to the sound from inside the bocal instead of what is coming out of the resonance of the rest of the instrument. A hole has to be drilled in the bocal with this approach. I like to use this whenever I can, as it basically eliminates the problem of feedback. But the sound is different. For some pieces, this isn't a problem as the sound is going to be changed anyways. As a comparison, let's listen to this clip of a piece called Concatenation with a regular microphone. (clip) Now let's listen to the same thing with an electric bocal. (clip) That's a pretty big difference in sound, but it's not a bad sound. It's also worth remembering that the acoustic sound of the bassoon will likely still be sounding in the room. Here is a mixture of the acoustic bassoon mixed with the effects from the electric bocal. It's a pretty good compromise in my opinion.

Until recently, the Little Jake pickup was the best option for bassoon. But with the passing of Trent Jacobs I'm not sure exactly what the future will hold. The company Piezo Barrel makes a pickup that is designed for clarinet barrels, saxophone mouthpieces, and others. I know it has been used with the bassoon, but I don't have any experience with it. Another promising option is the IntraMic. It's still in development, but Paul Hanson is using one. The advantage of the IntraMic is that you don't attach it to the bocal and you don't have to drill a hole in it. But it is expensive, around $800. With any of these options, there is some sort of a preamp that boosts the signal before going into other devices. I got my little-jake from forrests and at the time it came inside an altoids tin, but there are other options.
*** Cables (1 min)
Regardless of which method for capturing the bassoon is used, you need some sort of cable that connects to the computer. Microphones commonly use what is called an XLR cable. This is what it looks like. Electric bocals use a 1/4" cable that is the same on both sides. This is what that looks like. There are actually two types of 1/4" cables, balanced and unbalanced. The difference is in the ring of the connection. Balanced cables are often called tip ring sleeve or TRS cables, while unbalanced are just tip sleeve or TS cables. Effects pedals often use TS unbalanced connections, while other hardware tends to use the TRS balanced connection.
** Processing (20 minutes total)
Now we move to the processing stage of the system. Our microphones are capturing the wonderful sounds of the bassoon, but nothing is happening yet. We haven't plugged in our cables to anything that will process the sound. Here is where we branch into two paths: effects pedals versus personal computers. 
*** Effects Pedals (5 min)
Let's start with effects pedals. As I said earlier, it is easiest to use an electric bocal with effects pedals. Part of the reason is that electric bocals use cables that effects pedals use as input. Nearly all guitar effects pedals use an unbalanced 1/4" connection. While there is a huge variety of effects, most of them fit into the broad categories of distortion and its cousins overdive and fuzz, modulation featuring flangers, phasers, and pitch shifting, delays that include echoes, reverb, and loops, and filters like wah pedals and envelope filters. You can find individual stompboxes that basically hold one effect, like this envelope filter pedal, or bigger units called multi-effects pedals like this one. This pedal has over a hundred effects that can pair 7 effects at once and store 75 configurations of those effects. Some musicians prefer stompboxes because they can use an exact distortion pedal they like and can create their own pedalboard with their personal choice of effects in a chain of stompboxes. They also are cheaper and can be purchased gradually as you need them. Multieffect units on the other hand are great because you get lots of effects in one device. You might not have quite as much control over the effect or you might not like the tone of some of the effects. They are also more expensive as an initial cost, although buying a hundred stompboxes to replicate all the effects would be more expensive, but most people don't need that many effects. In fact, for most bassoon music you can do a lot with just a good delay, distortion, and octave pedal. It mostly depends on the repertoire you want to play and what it requires; more on that later.

Once the sound goes into the effects pedals, the effects chain will do its thing and get the sound ready for output. Effects are often turned on or off by stepping on a switch. They could be small metal ones like the ones on this pedal, or more of a big black button like the one on this pedal. If you have to change multiple stompboxes at once, you probably want to be sitting down in your performance, or hope you have some rests so you can hit both of them. Multieffects units often simplify this with their presets, and changing the preset with one footswitch can change all of the effects at once. After the sound has passed through all of the effects in the chain, it then goes to the output stage.
*** Computers (12 min)
Let's return now to the other branch of computer based processing.
**** Audio Interface 
Computers don't have microphone ports or 1/4" ports, so we need something that acts as a bridge between our cables and the computer. The easiest method I think is to use an audio interface. Simply put, an audio interface lets a computer hear what a microphone captures and also provides outputs from the computer that can connect to a speaker. Interfaces differ in the types and number of inputs and outputs, ranging from a basic 1 input 2 output interface to larger units that can handle 20 inputs and outputs. Most of the time we only need two or three inputs. For outputs two is often enough, and even pieces that use more can often be condensed down to a two-speaker version. Not many pieces use more than four outputs. Here is my audio interface. It has four combined XLR and 1/4" inputs on the front of the unit with different volume controls. On the back there are lots of output options. It only has two xlr outputs, but has four 1/4" outputs as well as 4 RCA outputs that I don't think I have ever used. This one also has MIDI ports that we'll talk about later. Almost all interfaces connect with a computer through a USB port, and that is how the computer gains access to all of the other parts of the system.
**** Software
So now that the computer can hear what we are playing, it becomes an active part of the system. Composers use programming languages to create programs or patches that can do all sorts of things, from playing fixed media sections on cue, to adding effects to the sound like pedals do, to creating an improvisation partner. Fortunately, we as performers don't need to be trained programmers to play the music. There are three different programs or languages that most composers use to create these patches: Max/MSP, Pure Data or PD, and SuperCollider. Max/MSP is by far the most popular, so we'll focus on that one. Pure Data is very similar to Max and is open source, which means it is free to use. SuperCollider is also open source, but takes a more traditional programming language approach of typing code. It is very powerful, but tends to be more intimidating to non programmers. Basically the way it works is anyone can use Max for free to open patches and run them, but if you want to create new patches or save changes to other patches, you need to pay for a license to the program. So for performers they're basically all free! So let's dive in a bit more on Max/MSP.
***** Max/MSP
One of the first things to do before running a Max patch is to tell the computer about your setup. That usually means selecting your audio interface as the input device and the output device. It could be more complex than that depending on what hardware is being used. For example in this classroom, I don't have a way to connect my audio interface to the speakers without running wire and doing things the University would not like me to do. So I have to use a different output device than my interface.

Now let's look at a max patch. It's very similar to opening a word document, or any other document from a program. The patch will come from the composer, usually in a zip file. Inside the zipped folder there will usually be a lot of patches depending on the programming approach of the composer. Usually there is one that has the name main patch or the title of the piece, or something that tells you it is the main patch. In this case it is Crook'd .  So I can either double click this file and it will open in max, or from max I can choose open file and find it that way. Here is what this patch looks like when we open it.

Max and Pd are both what we call visual programming languages, meaning that instead of typing code we create objects and connect them with imaginary cables. Often, composers try and organize it to make it easy to use while hiding the details that are unimportant for the performance. You can see there are buttons, sliders, meters, text boxes and more. If I undo the work of the composer to make it look good, here is what it looks like. Lots of little boxes with wire connections between them. Again, don't be intimidated by this, because the composer is the one that deals with all of this. We just have to look at this portion.

So now we have a max patch open, we've told the computer what our setup is like, now we have to tell max to do its thing. Usually there is a button somewhere that looks like a microphone or a speaker that we click to turn on the audio processing. There may be some instructions somewhere to hit a button before starting the piece to set all of the settings. Unfortunately each piece will be a little bit different because the composer can program it however they want. There's no set standard. But usually composers do well to document their patches so you can figure it out by reading what's on the screen. In this case, it says we click here to turn on the audio and then we're ready. Now most patches require going through a set of cues that are triggered throughout the performance, sometimes while we are playing. It is often not possible to play the bassoon and press buttons on the screen at the same time. This is where MIDI often comes in.

*** MIDI Controllers (2 min)
MIDI stands for Musical Instrument Digital Interface, and was developed in the 80s to communicate between different musical devices. MIDI does not actually contain sound, even though that is usually the desired result, but sends messages like play this note for this amount of time. Or change this control value to this number. If you've ever used a keyboard to input music in finale, sibelius, dorico etc. you have used a MIDI device. The keyboard sends MIDI messages when keys or buttons are pressed. We essentally do the same thing with Max. In fact, you probably could use that same midi piano keyboard to control Max, but it's often not much easier than hitting buttons on a screen. There are also MIDI foot pedals that can be programmed to do the same thing. Here are just two examples. The Behringer FCB1010 is a great unit that will do almost anything you could want with MIDI. It's a bit bulky when all you usually need is one of those buttons per piece, but it's a good choice for having the flexibility of anything that might be needed. This MIDI captain duo is a new one to me, and I'm really liking it so far. It is a bit more like programming to configure it, but hopefully isn't too bad. Again, a tech savy student or colleague could figure it out pretty quickly. This will do almost everything you need for most Max pieces. By far the most common MIDI message is sending what's called a continuous control message. Most patches will respond to sending value 127 to controller 64, which traditionally is pressing the sustain pedal. The traditional MIDI connection looks like this, but more devices are using USB to transfer MIDI information. MIDI controllers can connect directly to the computer through a usb connection, or to an audio interface through its MIDI ports. 
**** Selecting midi in max/msp?
So to recap the processing phase for pieces with computer processing: an audio interface brings in the signal from the microphones so the computer can hear it. Then the computer uses software, usually a Max/MSP patch, to process the sound when the performer tells the patch to do its thing. Often this is done by pushing a foot pedal, not unlike using effects pedals. Then the program will do whatever the composer designed it to do, and it brings us to the output phase of the system. 
** Output (6 min)
I'm going to keep going with the computer branch since that is what is most fresh in our minds.
*** Audio Interface
After the computer has done its processing, it will send the sound output back to the audio interface through its USB connection. This will often be two channels of audio, one for the left speaker and one for the right. However it could also be four channel output to have two speakers behind the audience, or in extreme cases even thirteen speakers! The outputs on the audio interface determine what is possible. Often powered pa speakers will be what the audio interface connects to. They often have the same combo XLR and 1/4" cables that the inputs of audio interfaces do. Many audio interfaces will use 1/4" outputs instead of XLRs because of the size of the ports. These should be balanced TRS 1/4" connections instead of the TS guitar cables. Usually the output levels can be controlled from the back of the speaker, the audio interface,  as well as adjustments in the max patch itself.  You will almost always need someone to help you sound check, because you can't be in the hall and on stage at the same time, and the acoustics of speakers and performance spaces make it difficult for the performer to really know what the balance is like for the audience. 

Where the speakers are placed will have a big impact on what the performer can hear on stage, as well as issues with feedback. Some are big proponents of having the speakers be on stage close to the performer so it sounds like the sound is coming from the performer, this makes it easier for the performere to hear, but often interferes with microphones that are also near the performer. Some like the speakers to be at the edge of the stage, mostly if they are using spatialization effects. Speakers are very directional, as opposed to the bassoon which has a diffuse sound. A good starting point, feedback allowing, is to have the speakers 30 degrees off center to give maximum stereo covereage to the audience. 

Returning to the effects pedals branch, it is most common to use a guitar or bass amplifier. They use the same TS cables that the effects pedals do. Each pedal has at least one 1/4" output jack that will be connected to the input of the amp. The volume controls are on the amp, as well as tone settings. Often the choice of amp can have as much an effect on the overall sound as the choice of different distortion pedals would. If you need more than one speaker, you have a couple of options. Some pedals have stereo outputs, so you could have two amplifiers angled 30 degrees off center just like you do with PA speakers. Another option is to put a dynamic microphone in front of the amp and use a mixer to send that sound to PA speakers. If you want to plug directly into a mixer you need what's called a DI box, that converts the unbalanced signal from the pedals into the balanced signal that the mixer expects. Note that when you do this, you are missing all of the tone that the amp normally gives to the sound.

So in summary, for any live electronics piece you have to capture the input of the bassoon, then get it into a computer of some sort that is often controlled by a foot pedal. Then you connect this computer to a speaker and do a good soundcheck and you're ready!
* Practical Example: Bassoonification (3 min)
I thought it would be helpful to review all of this again with a specific piece. The piece I'm going to play for you is called "Bassoonification" by Dan VanHassel. One of the reasons I am performing this piece is that I think it is one of the best candidates for someone's first piece with computer processing. It's an accessible piece, not too hard technically, and the electronics aren't too difficult either. So let's walk through the input, processing, and output phases again.
** Input
I'm going to use my little jake bocal as my microphone. I don't have to worry about feedback and I think the sound differences don't detract too much from the piece. So the little-jake plugs into the preamp, and then I am plugging it into the audio interface.

OR

I can't use my audio interface, so I'm actually going to use my Zoom H2N. It can act as an audio interface when it's plugged in by USB. 
*** Either electric bocal, or H2N depening on what I can get away with
** Processing
Now back in Max, I'm going to set the inputs and ouputs to be my audio interface.

OR

Set the input to my H2N and the output to HDMI

Now I open the patch, and see that I need to push this button to turn on the audio. It will advance with the space bar, or a value of 127 on controller 64. I'm going to use my MIDI captain to send that. Just a quick test, and we see that the cue is advancing. Now I'll reset the patch so I can start over.
*** Max/MSP load patch, select input/output
** Output
For the output, I'm using the HDMI from the computer because that's how I can interact with the speakers available. I'm going to play the first cue now just to make sure things are working and adjust balance.

Now that everything is set, I hope you enjoy Bassoonification.
* Performance of Bassoonification (7min)
* Reveal Website (3 min)
The next challenge you might be thinking about is where can I find the repertoire? And how do I know what equipment I need or if what I have will work for other pieces? This was a big part of my dissertation research, and I have created a website called the electric bassoon at electricbassoon.org. I would like to show you a few things from the site. 

First, there are pages devoted to performance practice that will explain many of the issues we talked about today in a bit more depth. It covers the input, processing, and output parts of the performance system as well as some other details about performing in this style, recommendations of gear, etc.

However, the bibliography is what shines. Here I have catalogues every piece that I was able to find in my research for pieces with effects pedals and with computers. No doubt I have missed some, but I don't think very many. Some pieces don't have as much information because composers didn't contact me, but most pieces should have sections about the necessary equipment, a diagram of the stage setup, screenshots of max patches and notation, recordings, and comments about the difficulty and style of the piece. 

As a quick example let's glance at Perfectly Logical that some of us heard yesterday. There's a link to Tawnie Olson's website where you can ask her about the piece, because most of these pieces are self published and you have to contact the composer directly
. There's a diagram of one variation of the stage setup. You can click on it to view the full size of the image. There's a glimpse of what the score looks like, which is pretty normal in this case. Then there's recordings on YouTube of the piece, and comments about difficulty and style.

Also there is a page of recommended beginning pieces, with the perspective of an undergraduate student as well as a professional who is new to electronics. This is a great starting point if you want to get into these pieces. If you already have some experience, then hopefully there are other pieces in the bibliography you don't know yet that you will enjoy. 

Of course, if you know of a piece and don't see it here, please let me know about it! I want this website to be as complete as possible and as helpful as possible to prospective performers like you!

* Questions
I think we have a few minutes left for questions, so what questions do you have?


* TODO 
Add pictures of microphones
Add picture of midi cable
Add some more transition buffers
