:PROPERTIES:
:ID:       f7a6944a-8b9b-41d3-8587-352a210ac62a
:END:
#+title: alterations to the tube

* Windsor Mill Process
This process was originally used to prevent cracks going into the blade as an alternative to the sink method. It also undampens the reed linearly, making an easier blowing reed. The fibers inside the blade vibrate more freely because they are shorter and cut off near the collar. The more cane taken out of the tube the greater the effect. It drops the overall pitch of the crows, and make for a little more space inside the reed. The effects are also more noticeable the further into the blades it is done.
** Method
1) Mark 32mm from the butt on each side (2mm past the collar)
2) Make a pilot cut using the smallest scraping wheel (#16 or #20). Remove up to .2mm from the center, but not going thinner than 1.10mm. With the wheel, each stroke removes about .01mm so count and measure frequently
3) Draw a sawtooth line along the tube with a pencil, then use a #32 scraper on the original cut until the pencil is gone
4) Sand inside with 400WD, including some transition into the blades
* Reverse Corona Variation
This variation thins the sides, allowing the sides of the tube to be pulled together more. It lets the blades bury in front of the collar more, creating a rounder tube. The overall effect dampens the reed, and gives a darker quality and rounder tube. Thus, it compliments the tip taper reed more than the straight taper reed. It is done at the same time Windsor Mill would be used, after GSP but before forming.
** Method
1) Mark the collar 30mm from the butt
2) Use a scraping wheel larger than the diameter of the cane (probably #36 or #40) and scrape from collar to butt ten times on both sides
3) From 3 to 5mm into the blade, scrape a transitional slope to the tube following the shape (unsure what the scrape is with, same wheel?)
4) Draw a sawtooth pattern with a pencil on the tube and use a #32 wheel until the pencil is gone. This reestablishes the inside diameter from before step 1
* Four Flats with Take-Out Variation
This process takes the edges of the tube out. It leaves stronger sides than the reverse corona. The effect is to free up the vibrations of the blades, giving a brighter timbre and easily blowing reed. It is done at the same GSP point of the other variations.
** Method
1) Mark the collar at 30mm and another mark at 35mm from each butt
2) With a sapphire file, flatten the edges of the tube and 5mm into the blades. The flat sides should be between 1 and 1.5mm wide and taper to nothing at the 5mm mark.
3) Using a small scraper like #16 or #20, take out the bump or shoulder from the inside of the flattened edge
4) Re-establish a 2.54mm radius with a #32 wheel from collar to butt. Smooth with 200 DRY and 400WD

The reverse corona leaves thinner sides and less space inside the tube. The four flats has a stronger tube that resists being pulled together and has more space inside the tube from the take-out variation.
* Tube Taper
This is an alternative to removing the flare from the shape. It thins the tube, which lets wire 3 be tighter and using the second wire as a fulcrum to push the tip open. It is also done at the same GSP phase.
** Method
1) Mark 18mm (wire 2) from butt end on the inside of each side of the cane
2) Take tape measuring 9mm x 20mm x .3 or .32mm (three pieces of masking tape) at the far end of the gouger bed. This bumps the end of the cane up at an angle
3) Re gouge from the 18mm to the butt end and drop the thickness of the butt by .4mm

This could also be done using a #24 scraping wheel
Also, you should use a contra mandrel for forming since the tube is bigger at the end.
* Beveling Variation
This is required if the flare is not removed, but it can be done to any reed. It's an asymmetrical bevel.
** Method
1)Use an exacto knife, cut an increasing amount of cane at a 30 degree angle on the inside edgeof the tube on the right side.

There is also a note about the /right champfer/ that takes cane at a 45 degree angle from the outside of the cane. This replaces the reverse corona in thinning the sides but doesn't change the inside radius of the cane. So there is more space inside the reed to give it a deeper sound.
[[cite:&mckay93_bassoon_reed_manual]]
