:PROPERTIES:
:ID:       4adab6df-42c5-4350-92b0-2b23ceb1a925
:END:
#+title: gouge


Gouging was originally tapered, which led to longer lasting reeds. This changed in the name of efficiency with machine gougers. Skinner's methods are somewhat based on the historical alterations to the gouge. 

Eccentric gouging gives stronger support to the pith in the spine. 

[[cite:&schillinger16_bassoon_reed_makin]]

There are two main types of gouges, the concentric gouge and the eccentric gouge. There's also inverted and closer to eliptical. Eccentric gouges are smaller inside the tube, and so have less depth, but a harder outline to the sound. This comes from the sides of reed having harder cane as compared to concentric gouges. Concentric gouges have a more homogenous sound because the highs and lows come from the same depth of cane. The preferred gouge for tip taper reeds is concentric, and eccentric for straight taper reeds (although Cooper likes eccentric with his tip taper reeds). Despite this, he recommends cane that is 1.25mm in the center and .8 at the edges. [[cite:&mckay93_bassoon_reed_manual]]


[[id:55a8d9af-61b1-4d29-bd61-05a9402bb519][Cane selection]]
