:PROPERTIES:
:ID:       ef2ccb2c-0b5c-496a-b17e-dff69db533c9
:END:
#+title: First sounds


To produce the crow with proper emouchure:
1) Whistle the lowest pitch you can produce
2) Whistle that pitch up one octave, noting the tightening of muscles to get higher. This is similar to the muscles used when playing bassoon.
3) Tighten those muscles until the whistle is lost. This is the basis of the embouchure.
4) Yawn to feel the pivoting motion of the jaw's hinge
5) With the jaw somewhat down and back, use that embouchure and blow as if blowing out candles on a birthday cake, this should get the crow

Then to get the first notes with proper embouchure:
1) Crow the reed several times
2) Place the reed on the bocal alone, getting the four semi-tone range of the bocal, special attention to getting the B (see reed criteria in chapter 3)
3) Assemble the bassoon
4) Crow again several times
5) Get ready to play

Then we get the first sounds
1) Finger C, ,and blow exactly how the crow was no matter how bad it sounds
2) Get the embouchure so that it sounds a B
3) If it isn't flat enough, they need to relax the embouchure, go back to reed or just reed and bocal

Then we bring it up
1) Add breath support to raise it to a C. Not by biting!!!!!
2) Repeat until a full resonant in tune sound can be produced with just breath support.
3) Recognize pitch level is primarily maintained by breath support

This gets a charactersitci bassoon sound in a minimum legnth of time (usually within the first lesson)

[[cite:&morris05_teach_method_lewis_hugh_cooper]]
