:PROPERTIES:
:ID:       56805d02-4fbf-48a6-9feb-1c2e65454e1b
:END:
#+title: hand profiling

First, mark the center of the cane on the bark side with a pencil. Then mark the outer limits of the blade profile, which is about 25.4mm or one inch. Then using an exacto knife, or other thin sharp blade, notch those pencil marks. The center mark should be fairly deep, and just through the bark on the outer marks. If using eccentricly gouged cane, make sure to not go through the entire piece of cane on the edges. Then, using the same knife, pull from the collar area to the center mark. This is just taking the bark off. It should be done in a minimum of 9-10 sections. Then, make an arrow head pattern on each blade, still from far point to center. The cuts should gradually deepen towards the center. The same 9-10 sections should be used. The sections on the side should go all the way to the collar. Then use a file to take out the ridges between each of these cuts. The center line needs to be around .38mm thick so that it won't break when you fold it over. Find the spot on each blade that matches what the desired back of the reed should be (.71mm for Cooper). The points should be equidistant from the center. If they aren't sand or file the thicker one to match the other one. These will be used to create the back of the reed later. Remeasures the center and mark it again. Inaccuracies count double here, so make sure it's right!. Rescore that mark.

[[cite:&cooper08_reed_makin_notes_two]]

This supposedly can be done quite quickly. It seems more of a ballpark profile to me that will be finished in more detail later.
