:PROPERTIES:
:ID:       257fac7f-b804-41db-aab8-66c2a38256e9
:END:
#+title: Hugh Lewis Cooper

Cooper taught very rigorous cane selection. He would use a dial indicator to correct imperfections in the gouge. He would soak dry and repeat until it was stable.

Cane preparation was more time consuming than finishing.

Tip apertures that can't be fixed imply a failed reed.

Reed making takes risks:
"Progress beyond [reed finishing] involves a creative procedure that, if successful, elevates the mechanical craft of reed making to the level of an art form. Suffice to say that only those individuals willing to risk losing a few second stage reeds can hope to aspire to this higher standard of excellence."

His pedagogy is spread through many publications, so it's hard to track it all down and follow all of it.

[[cite:&schillinger16_bassoon_reed_makin]] 127-139


His selection of cane is described in [[id:55a8d9af-61b1-4d29-bd61-05a9402bb519][Cane selection]]

Then see [[id:a8df25eb-7453-4398-aa98-ce835c896d54][preparing gouged cane]]

His reed soaking procedure is described in [[id:5ced6094-88e6-42cc-9ad2-f4355ccb08e4][soaking]].

His cubist approach tells how to [[id:56805d02-4fbf-48a6-9feb-1c2e65454e1b][hand profile]]

He prefers a [[id:50ef276c-13d8-48fb-962c-9a829508eab0][foldover shaper]]

He teaches about [[id:b53f863a-eccf-4a9a-8852-957a4cf6a199][shaping]]

His [[id:1b8ae276-07fe-407e-b3ec-69a32d5f826c][forming process]]

His [[id:53aea820-ca3b-48ee-a27b-5fd2187fc9c4][cooper finishing]] methods.

And finally his Knockenhauer [[id:c537e724-f66b-4453-ade2-775637d2b44f][measurements]]

He also stressed [[id:010bf0b0-b629-4b54-a820-c8999e732d94][reed contribution]] in the overall system.

[[id:41ff1af3-65d4-431d-b803-b8fee5cf37dd][7 Bassoon Reed Criteria]]
