:PROPERTIES:
:ID:       5caedef6-ec40-4069-b491-8fa4f4e103bc
:END:
#+title: Practicing

Weissenborn is first to talk about practice time. He says an hour daily, 20 minutes at a time, and then little by little make those 20 minutes be 30 minutes. After 3 to 4 months, two hours a day one hour at a time. After a year or so, three hours one at a time. More than that is seldom beneficial. [[cite:&schillinger16_bassoon_reed_makin]] 35

Having a good reed is important. To quote Almenraeder:
"The bassoonist, even when arriving at an advanced stage through study and practice, must nevertheless depend to a great extent upon his reed. He may have one of the finest instruments and may be in a perfect mind for practicing but if his reed is defective he will remain its slave; a slave to whom all freedom of movement is prohibited." [[cite:&schillinger16_bassoon_reed_makin]] 79


"Students must be trained to understand that the most important requirement for learning is practicing primarily for the purpose of detecting shortcomings and finding remedies for those shortcomings. When a student learns how to solve problems, a teacher is no longer necessary." - Norman Herzberg  [[cite:&lowe08_norman_herzb]]

"We must learn to take advantage of the assets of our instrument and reeds, and must acquire skills to compensate for their liabilities. To execute what we aspire to as performers requires in daily practice, systematic, conscientious, and expert appraisal of our abilities and disabilities, emphasizing always a disciplined and focused diligence in overcoming our weaknesses." - Norman Herzberg [[cite:&lowe08_norman_herzb]]

"The essentials of practice fall into three categories: scales, long notes and intervals. During practicing of these essentials, sensitivity to and skill with reed correction develops. Reeds must be improved and not blamed. I believe that reeds must closely approach or be equal to the tasks you demand of them. Your playing skills must fill in the gaps that reeds leave open." - Norman Herzberg [[cite:&lowe08_norman_herzb]]

Good reeds are important, but nothing is more important than practicing - Herzberg

"I would be remiss if I did not emphasize that proper bassoon practice is necessary in order to be an accomplished reed maker. Your reeds will be better only when you make demands on them and those demands are defined by your playing deficiencies. Practicing reveals shortcomings and knowledge of reed making can help eliminate difficulties. As you become a better performer your reeds must improve. Proper practice must include disciplined routines for scales, intervals, and long tones. Trying a reed by random playing does not define it as much as scales with different articulations over the whole range of the bassoon, long tones on problematic pitches and slurred intervals over the range of the instrument.” - Norman Herzberg [[cite:&lowe08_norman_herzb]]
