:PROPERTIES:
:ID:       5ced6094-88e6-42cc-9ad2-f4355ccb08e4
:END:
#+title: soaking

Soaking cane for a long time seems to have great benefits! Lacy says that 5 days should be the minimum, it will take out all of the sodium and other water soluble salts in the cane. Cane has a more uniform color, the texture is consistent, no need to break reeds in, reeds last longer, and reed making is more consistent!

You should use distilled water, in a tightly covered container, in the dark. Change the water every 48 hours. 5 days is enough, but it can go up to 8 months.

[[cite:&lacy88_exper_treat_arund_donax]]

Given that Lacy is a student of Cooper, it makes sense that these two sources would support each other, but here is Cooper's method that's a little more extreme than Lacy's initial experiment:

Prolonged soaking leaches out soluble saps and minerals from the cane. It also has a side benefit of making cane less allergy prone (the reason for this process's discovery). It also minimizes the break-in process. Playing on the reed very slowly brings out those salts and saps. Hot tap water can be used, but distilled water is probably better, especially for the permanent soaking cane. Start with changing the water every 24 hours, until the water stays clear for a day or two at a time. At this point, the cane can be put in permanent soaking water, as long as it stays in a dark place, and has minimal air in the container. The peak quality is after two to three months. If signs of algae or mold appear, clear out the water, rinse the cane, and hope it works out. If it persists, it's best to just make the reeds.

His suggested experimentation is to take 25-30 pieces of cane and soak them to the perma storage state, then let them sit for 2 to 3 weeks. After this, make 2-3 reeds a week and note their characterstics. They should get better as the end comes.

[[cite:&cooper91_reed_makin_notes]]

Skinner recommended soaking cane for 5 days—changing water every day—before gouging. He also says to drain the water after 5 days and leave the cane covered for two more days. I'm not sure what his point was for this. After gouging, he would soak the cane and dry it again so that the grain wouldn't rise again. [[cite:&mckay93_bassoon_reed_manual]] Cooper does something a bit faster.
