:PROPERTIES:
:ID:       5f69f4b4-88e4-4a0b-99e6-5494e651ac4e
:END:
#+title: skinner tools

* Scraping wheels
Wheels used to alter the inside of the gouge. He had wheels in various sizes; the radius of the wheels he used were 16/32 (of an inch), 20/32, 24/32, 28/32, 30/32, 32/32, 36/32, 40/32, 48/32, and occasionally a 56/32 and 64/32. James McKay demonstrated their use in a video where you hold it like a pencil and drag it backwards in the scraping direcion.
* Mandrels
He used 4 pin mandrels, a #9 (9/64"), #10 (10/64"), #11 (11/64") and #13 (13/64" mostly used for contra reeds). The #9 was used for opening the first wire in straight taper reeds and to make the first wire more oval. #10 and #11 were for straight taper reeds because of the rounder tubes. 

For forming mandrels he used a 10/12 mandrel that starts at 12/64" and tapers to 10/64" at the end before the point. It has an insert mark 1" from the point. This mandrel was used when the flare of the shape was removed. #10 or #11 mandrels were used when the flare wasn't removed.
* Reamers
He used a drill bit that was 3/16" mounted in a handle. He inserted it 18mm(to the second wire). Then he had a conical reamer made from a rattail file (also 3/16") that was only inserted 17mm. He used a slightly larger reamer if the reed leaked on the bocal. There's also a #9 machinists drill if the flare was left on the shape.
* Shapers
He had lots, but the Fox #2 is most common in the book. He also made some templates out of brass and used masking tape to make a copy for a reed.
* Knives and Plaques
He required at least 3 knives. A "regular knife" for trimming work to scrape the blades without chattering. He also liked a knife with a heavy spine for pre trim and hand profiling. It has to be heavy enough to not chatter when removing bark. Then he used #11 exacto blades for shaping, scoring, and other miscellaneous tasks.
* Files and Sandpaper
He used the flat bastard, rattail, and knife edge files. The flat bastard could be used as an alternative to the knife for working on blades. The knife edge is for marking spots for wires and collars on cane. Rattail is to clean the tube. Sometimes he used a sapphire file to do fine work on the blade or in the take-out variation.

Sandpaper should be in five grades: 120 Dry, 200 Dry, 220WD, 320WD, and 400WD. They should be cut in strips of 15mm by 5cm and folded for ease of use. For the tip undercut, it should be cut in strips .9cm x 5cm.
* Pliers and End-nippers
Parallel jaw pliers are great for adjustments. Needle nose pliers are also reocmmended for between wires 2 and 3. 5 inch jewelers end nippers are recommended for cutting the tip.
* Rulers, Dividers, and Compasses
Need a basic 6 inch metal ruler with 0 at the end. He also used lots of dividers and compasses. There are so many common measures that having lots of them is helpful to avoid resetting measurements for everything. Calipers are also good for measuring the width of tubes.
* Other tools
Dial indicators are useful for measurements. 1 1/4" dowels for drying gouged cane. An easel is useful for pre trim and hand profiling. A lamp is good for examining reeds under light.

[[cite:&mckay93_bassoon_reed_manual]]
