:PROPERTIES:
:ID:       3faea275-8fff-4326-98b3-dbe820263410
:END:
#+title: hite-estevez burnout
#+filetags: :idrs:2025:burnout:joy:creativity:

Notes from lecture given at IDRS 2025 at Butler.

"Alive"= joyful, energized, good-timed, excited, hopeful

When was the last time you felt alive?

Who am I beyond what I do?
- 70s psychologist Fruedenberger
- prolonged stress

"I need to be the best" "I need to create more"

"The Artsits Way"
"Burnout: The Secret to Unlocking the Stress Cycle"

Stressor->Resistance->Exhaustion

We aren't completing the stress cycle

Strive to complete stress cycle every day

Preventing burnout strategies:
- Physical activity 20-60 minutes per day
- Breathing
- Positive Social Intreraction (small talk)
- Laughter (especially in community)
- Affection (hug) -> 20 seconds
- A big ol' cry (sad movies too for hacking)
- Creativity (rest, play, wonder)

What is creativity?
- making things you care about
- intelligence having fun

Just because you work in creative fields doesn't mean you are experiencing the benefits of creativeity in your life

Joy of unexpected result thrills burnout

It's ok to take "no" from inanimate object
Where is the thrill of "what happens next?"
Don't pick up what is not yours to carry
Name limits. What's the bottom line of what you'll endure?
Self care vs self comfort
What in this music brings you joy?
