:PROPERTIES:
:ID:       3212399e-a1c6-44ce-a32b-e86bb35d13e2
:ROAM_REFS: cite:benedictis18_author_perfor_tradit_age_techn
:END:
#+title: benedictis18_author_perfor_tradit_age_techn

* Authorship and Performance Tradition in the Age of Technology

** page 196
Authorship is the relationship that holds between an author and a /text/, the manner in which a /text/ apparently points tot his figure who is outside and precedes it.

Applying this to music is problematic.

Is authorial synonymous with authentic?

Could there be multiple authors? One of the text and one of the performance?

Authorial intention remains and unsovled problem in literary and musical studies.

** page 197
Authoriality vs freedom of performance is not an antithesis.
The authorial performances tend to be freer than non authorial counterparts.

If the circle of author, text, performance only sort of works in classical-romantic rep, it is a crisis in some modern music
** page 200
discourse about a "free" piece by Berio that he rewrote because the performers took "too much" freedom. Are recordings before the rewrite no longer authorial?
** page 209
Berio frequently changed his pieces based off what he learned from previous perfomances. So how does this factor into authorship?
After an author dies, the interpretation more or less freezes

* Impression
This seemed to go over examples of why authorship is problematic, and that performance history changes a work throughout the composers lifetime. After the composer dies, it becomes an issue to decide which performance is the historically accurate performance.
