:PROPERTIES:
:ID:       a4ced4c8-dea9-47f4-ada8-35fc467c0897
:ROAM_REFS: cite:cooper09_slipp
:END:
#+title: cooper09_slipp

* Slippage
:PROPERTIES:
:NOTER_DOCUMENT: ../PDFs/cooper09_slip.pdf
:END:
** During Construction
:PROPERTIES:
:NOTER_PAGE: (1 0.3032069970845481 . 0.11028632025450692)
:END:
Slippage is predetermined during the tube forming stage. No one makes reeds without a little bit of slippage, so why not control its positive attributes?
** Leaf Spring
:PROPERTIES:
:NOTER_PAGE: (1 0.44314868804664725 . 0.12513255567338286)
:END:
Says that slipping the blades a little creates a "movable schackle" system analogous to a leaf-spring. It facilitates lateral motion when the sping is vertically flexed.
Reed tip increases when it closes, regardless of whether or not the tip is damped or undamped.
The shorter leaves of the spring are used when there is more pressure, and the blade is the same with different playing pressures.
** Better seal
:PROPERTIES:
:NOTER_PAGE: (2 0.11661807580174927 . 0.06574761399787914)
:END:
Slipped blades match better. Because it's easier to match an edge to a plane than an edge to and edge.
** Noise
:PROPERTIES:
:NOTER_PAGE: (2 0.37317784256559766 . 0.08059384941675506)
:END:
Slippage also helps the embouchre not have to dampen some of the unmusical noise of the rails.
** Flexibility
:PROPERTIES:
:NOTER_PAGE: (2 0.8017492711370262 . 0.08801696712619303)
:END:
You can torque your head to increase the slippage and darken the sound in performance
** Adjusting
:PROPERTIES:
:NOTER_PAGE: (2 0.8483965014577259 . 0.08801696712619303)
:END:
You can adjust slippage by gripping between the first and second wire with thumb and finger on one hand, then twist the turk's head in the opposite direction of the desired slippage. So turning it clockwise from the rear perspective will result in the top blade moving to the right from the front perspective. This is limited to the original right or left over-lapping during forming.
** Torquing the turks head
:PROPERTIES:
:NOTER_PAGE: (3 0.40816326530612246 . 0.10286320254506895)
:END:
One of the two ways to adjust the inner reed cavity of a finished reed
** Results
:PROPERTIES:
:NOTER_PAGE: (3 0.478134110787172 . 0.12513255567338286)
:END:
More slippage = narrower blade width
Less slippage = wider blade width
If you go too far, dial it back and try again
If you need more turn the turks head a little more
*This only works if you don't put duco or similar on the tube underneath the wrapping*
** Four Slippage Patterns
:PROPERTIES:
:NOTER_PAGE: (3 0.6467486818980668 . 0.11508951406649615)
:END:
Two modes, scissored and embraced. Two types are unacceptable and uncorrectable, so just throw them out.
Only one of the two acceptable types is compatible with an individual's emouchure. So being uncontrolled, 50-75% of reeds are doomed from the beginning.
** Causes
:PROPERTIES:
:NOTER_PAGE: (3 0.7592267135325131 . 0.12404092071611252)
:END:
Causes of the unacceptable forms include an inaccurate center folding of the cane that was shaped on a straight shaper (more evidence for foldover shaper)
Inaccurate shaper contour
Major crack on only one side of the tube in the blade area
** Types
:PROPERTIES:
:NOTER_PAGE: (4 0.11247803163444639 . 0.0971867007672634)
:END:
Scissored have one inner and one outer blade on each. These are acceptable, but apparently only one of the clockwise or counter clockwise directions works for any one person.
The bad ones are embraced, where one of the blades has two outer edges and one has two inner edges. These are unfixable.
** Finding directionality
:PROPERTIES:
:NOTER_PAGE: (4 0.44991212653778556 . 0.08823529411764704)
:END:
Using a mirror or observer to see the cant of the emouchre to the reed, or the reed from the bocal. If the top of the head rotates right, (most common) then the slip needs to be clockwise to the right. If it's left, then counterclockwise.
Another method is to look at successful reeds and see if there is a consistent slippage directionality. 
** Determining the slippage
:PROPERTIES:
:NOTER_PAGE: (4 0.9068541300527241 . 0.08823529411764704)
:END:
Once the directionality is found, then we must physically ensure the slippage before putting the wires on, but after beveling and scoring.
** Offset
:PROPERTIES:
:NOTER_PAGE: (5 0.1265377855887522 . 0.10613810741687978)
:END:
Offset the butt the opposite direction of desired slippage. The wires should also be turned opposite the desired slippage,
** To Unbelievers
:PROPERTIES:
:NOTER_PAGE: (6 0.1265377855887522 . 0.0971867007672634)
:END:
The slippage often occurs in the tube at the second wire, even if the tip does not show any slippage. The torquing in the tube stays dominant!
