:PROPERTIES:
:ID:       9dcb37bd-7787-4796-8d10-80d3c049326e
:ROAM_REFS: cite:herzberg01_reedm
:END:
#+title: herzberg01_reedm

* Herzberg
:PROPERTIES:
:NOTER_DOCUMENT: ../PDFs/herzberg01_reedm.pdf
:END:
** Grain and Pulp
:PROPERTIES:
:NOTER_PAGE: (1 0.3564695801199657 . 0.06138107416879793)
:END:
Pulp is parenchyme, grain is sclerenchyme. The grain gives the strength to reinforce the pulp.
** Variance
:PROPERTIES:
:NOTER_PAGE: (1 0.6169665809768637 . 0.06138107416879793)
:END:
No two plants of cane are exactly alike
** Definition of good cane
:PROPERTIES:
:NOTER_PAGE: (1 0.7540702656383891 . 0.06138107416879793)
:END:
"A good piece of cane is one that responds to trimming and adjustments and maintains them. Conversly, a bad piece of cane will not respond and will require constant trimming and adjustment until there is no further adjustment or trimming possible."
** Crowing and measuring
:PROPERTIES:
:NOTER_PAGE: (1 0.8817480719794345 . 0.07928388746803067)
:END:
Dial indicator measurements and the crow are "fallacious" tests. Some good reeds don't crow, and some bad reeds crow really well.
** Reed making process
:PROPERTIES:
:NOTER_PAGE: (1 0.34704370179948585 . 0.5179028132992327)
:END:
Eliminate as much human error as possible in blank construction. Then find the solutions to deal with each piece of cane, of which there is an endless variety.
** Unique solutions
:PROPERTIES:
:NOTER_PAGE: (1 0.8800342759211653 . 0.5358056265984654)
:END:
"We must learn to trim reeds according to the response of each specific piece of cane"
** Traditional Methods
:PROPERTIES:
:NOTER_PAGE: (2 0.3427592116538132 . 0.08823529411764704)
:END:
So we are back to traditional methods since every piece of cane is different and can't be spit out on measurements alone.
** Four systems
:PROPERTIES:
:NOTER_PAGE: (2 0.47986289631533846 . 0.07928388746803067)
:END:
Shape, thickness, wires, and bevel.
** Arthur Weisberg quote
:PROPERTIES:
:NOTER_PAGE: (2 0.10968294772922023 . 0.5626598465473146)
:END:
"You get the reeds that you deserve" meaning that you need to work to get the good reeds.
