:Properties:
:ID:       49cab9c3-101f-4d56-bcb8-7e036ec9603a
:ROAM_REFS: cite:macdonald95_perfor_pract_presen_elect_music
:END:
#+TITLE: macdonald95_perfor_pract_presen_elect_music: Performance practice in the presentation of electroacoustic music

* Performance practice in the presentation of electroacoustic music
:PROPERTIES:
:Custom_ID: macdonald95_perfor_pract_presen_elect_music
:URL: 
:AUTHOR: MacDonald, A.
:NOTER_DOCUMENT: ~/dissertation/PDFs/macdonald95_perfor_pract_presen_elect_music.pdf
:NOTER_PAGE:
:END:
** Meaning
   :PROPERTIES:
   :NOTER_PAGE: (2 . 0.3883696780893042)
   :END:
Listeners have to comprehend some form of musical meaning, or they won't like the music. In electroacoustic music, that meaning is often something different than basic pitch or rhythmic structures. What comes out of speakers is an illusion, which could be an illusion of something real, surrel, or abstract.
** Source Attribution
   :PROPERTIES:
   :NOTER_PAGE: (3 . 0.5051229508196721)
   :END:
Listeners try and associate what physical action caused a sound, for example plucking, scraping, or striking. Even for unknown sounds, our brain tries to figure out what the cause may be.
** Spatial Structure
   :PROPERTIES:
   :NOTER_PAGE: (4 . 0.5399590163934426)
   :END:
Music structure relies heavily on spatial factors, so care must be taken in the public presentation to preserve meaning.
** Placement of Speakers
   :PROPERTIES:
   :NOTER_PAGE: (5 . 0.3483606557377049)
   :END:
Discussion of difficulties just using 2 speakers
