:PROPERTIES:
:ID:       c1489e1b-c45f-4d19-8fd0-92078f9b8462
:ROAM_REFS: cite:rogers04_teach_approac_music_theor
:END:
#+title: rogers04_teach_approac_music_theor

* Teaching Approaches to Music Theory
** Chapter 1
Scales, do-re-mi, roman numerals, and key signatures are no more a study of music than the alphabet, verbs, commas, etc. are studying literature. It is more pretheory. (pg 3)
All to often the terminology, labels, etc. take the entirety of music theory curriculum and it never gets applied. It's an introduction that runs out just at the wrong time. (pg 4)
One of the goals should be to discover what questions about music are worth asking in the first place. (pg 5)
Too often we teach with right-or-wrong exercises. We don't allow for creative thinking. It's too black and white. (pg 5)
Just because "correct" answers are hard or impossible to find, doesn't mean we should shy away from grappling with those questions. (pg 7)
Music theory is more of an activity like composition or performance, and less like a subject to learn. (pg 7)
thinking and listening are inseperable in theorizing (pg 8)
The urge to teach inside the box, black and white, right or wrong—because it makes our job easy—should be resisted at all costs. (pg 14)
** Chapter 2
** Chapter 3 Mind Training
*** Presenting New Material
Try and present new topics as an offshoot, variant, or relative of another. Stress similarities as much as differences.
Examples:
- Modulation vs secondary dominants (very similar processes, just more local vs global)
- N^6 vs IV (very similar in pitches, function, etc.)
- Anticipation vs suspension (both a temporal adjustment, both changing the goal, both have a dissonance and resolution)

This also builds review into a course, as everything is put in the context of what they already know. (pg 57)
Try to keep the essence simple, avoid overcomplicating things too early. For example, passing tones are simple, but listing 10-12 different types of passing tones is not good at the beginning. (pg 59)
Make sure to not skip over steps just because we are good at it, because the students may not be. If a student is struggling, keep breaking things into previous steps until there is some level of comprehension, then build from there. (pg 60)
Sometimes it is necessary to have a class or lecture that ties in topics that have been studied individually into one whole (pg 64)

** Chapter 4
** Chapter 5
** Chapter 6 Teaching Techniques
1) The single most important thing when teaching new material is to relate the strange to the familiar. Spiral learning and disguised repetition are easy to do in music theory
2) Distinguish between core essential concepts and peripheral material must be made. Student can't sort through this unless distinctions are made.
3) Assume only the student's background knowledge. Try to think what it will be like to learn things for the first time. Our job is to fool students into seeing that theory is simpler than they think it is
4) Present new material in a way that sets the stage for the next topic. Everything fits into a single continuum
5) Principles of programmed instruction (steps to solve a problem I think?) can be used in any theory course. Try and shift diagnosis of errors from teacher to student, let them figure out their mistakes. Are they careless? Wrong clef? Working too fast? Too slow? Not considering alternatives? Not understanding current topic? Lack of previous assumed knowledge?
6) Preparation and organization. Very few can consistently wing it. Make written notes for each class. Plan more activities than there is time for, as some things go quicker than anticipated. Stuff that isn't used can give continuity in the next class. Changing topics or approaches every 10-15 minutes is a good balance. Don't just spell things for the whole class period.
7) Verbally express high expectations. Students tend to live up to standards and hopes that are instilled in the classroom atmosphere.
8) Any improvements to physical classroom space should be taken advantage of. Temperature, air, light, windows, background sounds, speaker placement, seating arrangements
9) Students should be actively engaged as much as possible
10) Analysis and listening should reinforce each other
11) Multifaceted approaches are best for most teachers. It increases the chances for students to find what works for them.
12) Use students in teaching
13) Distinguish between drilling and teaching. Try and drill just enough so students know how to drill on their own. Let most of that happen outside of class
14) A review at the beginning of a new course or new year is often good.
15) Make minor adjustments, new pieces, etc to keep the course fresh. Don't try every single fad, that can be as disruptive as changing applied teachers every semester.
16) Computers can be helpful, but don't replace teaching. Computers are very good at what is least important in music theory, and not great at what is important. Computers can't really teach, they can only test.
(pages 153-161)
*** Teaching versus Learning
Group dynamics and communication are important, perhaps more than we like to admit.

Classes normally have three phsycological stages:
1) Dependency stage - first two or three weeks of the semester.
2) Affiliative stage - middle ten weeks
3) Closure stage - last 2-3 weeks
** Chapter 7 Evaluation and Curriculum Design
*** Testing and Grading
Suggestions for a valuable test:
1) Both fair and challenging. This is one of the hardest parts
2) Specifying content, length, difficulty level, etc. in advance increases the likelihood of study and preparation. Practice tests are often valued by students.
3) Lots of shorter tests are best so no single score is over-weighted. This is especially true in ear-training courses.
4) A variety of difficulty levels within the exam hel0p to spread scores appropriately (avoiding too many As or Fs). It is wise to start with some easy questions everyone can get to boost confidence. It's also wise to have a couple really hard questions to extend the strong students
5) Have students construct exams as well as take them.
6) Feedback (quick if possible) and review of test questions is important.
7) You can be creative and imaginative in test questions as much as other areas of teaching. Again, watch for only testing things easy to grade
8) Judging length is one of the harder things to do. Can have differences of speed tests and power tests
9) Distinctions should be made among domains of thinking to be tested. Mix subjective vs objective, sort answer, essay, symbols, facts, opinions, skills
10) Reliability and validity. Do repeated measures yield similar and consistent results? Does the test measure what it claims to measure?
11) Some pass/fail exams with high thresholds and very specific factual information can be helpful (an example is key signatures)
12) Self administered or self paced exams can be good in environments that allow for them
13) Distinctions between aptitude and achievement is complex but can be helpful in designing formats
14) Grading schemes is difficult. Percentage based, curve based, or contract based (meaning if you get to a certain level, you get an A. Is this like a rubric?)
15) Make sure whatever you do is clearly designed and stated in the syllabus
16) Teaching just for exams is a dangerous routine. Many of the most important goals can't be tested at all. Shouldn't be taken too seriously, but still get all the value and effort it needs
(pages 166-169)
*** Organization of a theory program
